import {mkdir, readFile, rm, writeFile} from 'node:fs/promises'
import path from 'node:path'
import {fileURLToPath, pathToFileURL} from 'node:url'

import openapiTS, {astToString} from 'openapi-typescript'

import {
  getUpstreamSource,
  isStableGeneratedOpenApiSource,
  isStableGeneratedOpenRpcSource,
} from '../../src/lib/upstream/manifest.ts'

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url))
const PROJECT_ROOT = path.resolve(SCRIPT_DIR, '../..')
const THIRD_PARTY_ROOT = path.join(PROJECT_ROOT, 'third_party', 'upstream-specs')
const GENERATED_ROOT = path.join(PROJECT_ROOT, 'src', 'generated')

const OUTPUTS = {
  'canton-json-ledger-api-openapi': {
    directory: 'ledger-json-api',
    fileName: 'canton-json-ledger-api.ts',
  },
  'splice-scan-external-openapi': {
    directory: 'splice',
    fileName: 'scan-external.ts',
  },
  'splice-ans-external-openapi': {
    directory: 'splice',
    fileName: 'ans-external.ts',
  },
  'splice-dapp-api-openrpc': {
    directory: 'openrpc',
    fileName: 'dapp-api.ts',
  },
}

function relativeFromProject(targetPath) {
  return path.relative(PROJECT_ROOT, targetPath).split(path.sep).join('/')
}

function buildMetadataLiteral(specEntry, stableGenerated) {
  return JSON.stringify(
    {
      sourceId: specEntry.sourceId,
      name: specEntry.name,
      family: specEntry.family,
      format: specEntry.format,
      stability: specEntry.stability,
      artifactVersion: specEntry.artifactVersion,
      fetchedAt: specEntry.fetchedAt,
      selectedSha256: specEntry.hashes.selectedSha256,
      upstream: specEntry.upstream,
      stableGenerated,
      thirdPartyDir: `third_party/upstream-specs/${specEntry.directory}`,
      selectedSpecFile: `third_party/upstream-specs/${specEntry.directory}/${specEntry.files.selected}`,
    },
    null,
    2,
  )
}

function buildHeader(specEntry) {
  return `/**
 * Generated by scripts/codegen/generate-types.mjs.
 * Source ID: ${specEntry.sourceId}
 * Upstream ref: ${specEntry.upstream.ref}
 * Artifact version: ${specEntry.artifactVersion ?? 'unknown'}
 * Fetched at: ${specEntry.fetchedAt}
 * SHA-256: ${specEntry.hashes.selectedSha256}
 */`
}

async function buildOpenApiModule(specEntry, metadataExportName) {
  const selectedSpecPath = specEntry.mirror?.entry
    ? path.join(THIRD_PARTY_ROOT, specEntry.directory, specEntry.mirror.entry)
    : path.join(THIRD_PARTY_ROOT, specEntry.directory, specEntry.files.selected)
  const ast = await openapiTS(pathToFileURL(selectedSpecPath))
  const typeSource = astToString(ast).trim()

  return `${buildHeader(specEntry)}

export const ${metadataExportName} = ${buildMetadataLiteral(specEntry, true)} as const

${typeSource}
`
}

async function buildOpenRpcModule(specEntry, metadataExportName, documentExportName) {
  const selectedSpecPath = path.join(THIRD_PARTY_ROOT, specEntry.directory, specEntry.files.selected)
  const documentText = await readFile(selectedSpecPath, 'utf8')
  const document = JSON.parse(documentText)

  return `${buildHeader(specEntry)}

export interface OpenRpcDocument {
  jsonrpc?: string
  info?: Record<string, unknown>
  methods?: Array<Record<string, unknown>>
  components?: Record<string, unknown>
  [key: string]: unknown
}

export const ${metadataExportName} = ${buildMetadataLiteral(specEntry, true)} as const

export const ${documentExportName}: OpenRpcDocument = ${JSON.stringify(document, null, 2)}
`
}

async function cleanGeneratedDirectories() {
  for (const directory of ['ledger-json-api', 'splice', 'openrpc']) {
    await rm(path.join(GENERATED_ROOT, directory), {force: true, recursive: true})
  }
}

function buildRegistryModule(specManifest) {
  const syncedRegistry = specManifest.sources.map(specEntry => {
    const source = getUpstreamSource(specEntry.sourceId)
    const stableGenerated = isStableGeneratedOpenApiSource(source) || isStableGeneratedOpenRpcSource(source)
    const output = OUTPUTS[specEntry.sourceId]

    return {
      sourceId: specEntry.sourceId,
      family: specEntry.family,
      format: specEntry.format,
      stability: specEntry.stability,
      stableGenerated,
      fetchedAt: specEntry.fetchedAt,
      selectedSha256: specEntry.hashes.selectedSha256,
      thirdPartyDir: `third_party/upstream-specs/${specEntry.directory}`,
      selectedSpecFile: `third_party/upstream-specs/${specEntry.directory}/${specEntry.files.selected}`,
      modulePath: stableGenerated && output ? `src/generated/${output.directory}/${output.fileName}` : null,
    }
  })

  const stableGeneratedSourceIds = syncedRegistry.filter(entry => entry.stableGenerated).map(entry => entry.sourceId)
  const stableGeneratedOpenApiSourceIds = specManifest.sources
    .filter(specEntry => isStableGeneratedOpenApiSource(getUpstreamSource(specEntry.sourceId)))
    .map(specEntry => specEntry.sourceId)
  const stableGeneratedOpenRpcSourceIds = specManifest.sources
    .filter(specEntry => isStableGeneratedOpenRpcSource(getUpstreamSource(specEntry.sourceId)))
    .map(specEntry => specEntry.sourceId)

  return `import type {
  UpstreamFamily,
  UpstreamFormat,
  UpstreamSourceId,
  UpstreamStabilityClass,
} from '../lib/upstream/manifest.js'

export interface SyncedSpecRegistryEntry {
  sourceId: UpstreamSourceId
  family: UpstreamFamily
  format: UpstreamFormat
  stability: UpstreamStabilityClass
  stableGenerated: boolean
  fetchedAt: string
  selectedSha256: string
  thirdPartyDir: string
  selectedSpecFile: string
  modulePath: string | null
}

export const SYNCED_SPEC_REGISTRY = ${JSON.stringify(syncedRegistry, null, 2)} as const satisfies readonly SyncedSpecRegistryEntry[]

export const STABLE_GENERATED_SOURCE_IDS = ${JSON.stringify(stableGeneratedSourceIds, null, 2)} as const satisfies readonly UpstreamSourceId[]
export const STABLE_GENERATED_OPENAPI_SOURCE_IDS = ${JSON.stringify(stableGeneratedOpenApiSourceIds, null, 2)} as const satisfies readonly UpstreamSourceId[]
export const STABLE_GENERATED_OPENRPC_SOURCE_IDS = ${JSON.stringify(stableGeneratedOpenRpcSourceIds, null, 2)} as const satisfies readonly UpstreamSourceId[]

export * as ledgerJsonApi from './ledger-json-api/index.js'
export * as splice from './splice/index.js'
export * as openrpc from './openrpc/index.js'
`
}

async function writeDirectoryIndexes() {
  await writeFile(
    path.join(GENERATED_ROOT, 'ledger-json-api', 'index.ts'),
    `export {cantonJsonLedgerApiMetadata} from './canton-json-ledger-api.js'
export type {
  components as CantonJsonLedgerApiComponents,
  operations as CantonJsonLedgerApiOperations,
  paths as CantonJsonLedgerApiPaths,
} from './canton-json-ledger-api.js'
`,
  )

  await writeFile(
    path.join(GENERATED_ROOT, 'splice', 'index.ts'),
    `export {spliceAnsExternalMetadata} from './ans-external.js'
export type {
  components as SpliceAnsExternalComponents,
  operations as SpliceAnsExternalOperations,
  paths as SpliceAnsExternalPaths,
} from './ans-external.js'

export {spliceScanExternalMetadata} from './scan-external.js'
export type {
  components as SpliceScanExternalComponents,
  operations as SpliceScanExternalOperations,
  paths as SpliceScanExternalPaths,
} from './scan-external.js'
`,
  )

  await writeFile(
    path.join(GENERATED_ROOT, 'openrpc', 'index.ts'),
    `export {
  spliceDappApiOpenRpcMetadata,
  spliceDappApiOpenRpcSpec,
} from './dapp-api.js'
export type {OpenRpcDocument} from './dapp-api.js'
`,
  )
}

async function main() {
  const specManifestPath = path.join(THIRD_PARTY_ROOT, 'manifest.json')
  const specManifest = JSON.parse(await readFile(specManifestPath, 'utf8'))

  await cleanGeneratedDirectories()
  await mkdir(path.join(GENERATED_ROOT, 'ledger-json-api'), {recursive: true})
  await mkdir(path.join(GENERATED_ROOT, 'splice'), {recursive: true})
  await mkdir(path.join(GENERATED_ROOT, 'openrpc'), {recursive: true})

  for (const specEntry of specManifest.sources) {
    const source = getUpstreamSource(specEntry.sourceId)
    const output = OUTPUTS[specEntry.sourceId]

    if (isStableGeneratedOpenApiSource(source)) {
      if (!output) {
        throw new Error(`Missing output mapping for ${specEntry.sourceId}`)
      }

      let metadataExportName
      if (specEntry.sourceId === 'canton-json-ledger-api-openapi') {
        metadataExportName = 'cantonJsonLedgerApiMetadata'
      } else if (specEntry.sourceId === 'splice-scan-external-openapi') {
        metadataExportName = 'spliceScanExternalMetadata'
      } else {
        metadataExportName = 'spliceAnsExternalMetadata'
      }

      const fileContents = await buildOpenApiModule(specEntry, metadataExportName)
      const outputPath = path.join(GENERATED_ROOT, output.directory, output.fileName)
      await writeFile(outputPath, fileContents)
      console.log(`generated ${relativeFromProject(outputPath)}`)
      continue
    }

    if (isStableGeneratedOpenRpcSource(source)) {
      if (!output) {
        throw new Error(`Missing output mapping for ${specEntry.sourceId}`)
      }

      const fileContents = await buildOpenRpcModule(
        specEntry,
        'spliceDappApiOpenRpcMetadata',
        'spliceDappApiOpenRpcSpec',
      )
      const outputPath = path.join(GENERATED_ROOT, output.directory, output.fileName)
      await writeFile(outputPath, fileContents)
      console.log(`generated ${relativeFromProject(outputPath)}`)
    }
  }

  await writeDirectoryIndexes()
  await writeFile(path.join(GENERATED_ROOT, 'index.ts'), buildRegistryModule(specManifest))

  console.log(`generated ${relativeFromProject(path.join(GENERATED_ROOT, 'index.ts'))}`)
}

await main()
